import analizador
print ("--------------------------------------------")
texto = input("Ingrese el texto a analizar: ")
print ("--------------------------------------------")
analizador = analizador.AnalizadorLexico()
analizador.analizador(texto)
analizador.getListaTokens()
print ("--------------------------------------------")
print("Salida")
print ("--------------------------------------------")
analizador.imprimirSalida()
print ("--------------------------------------------")
print("Pila")
print ("--------------------------------------------")
analizador.imprimirSintactico()
print ("--------------------------------------------")